# Publish on new commits on main and beta branch
deploy:
  stage: deploy
  only:
    - main
    - beta
  tags:
    - moralis-runner
  script:
    - cd /home/gitlab-runner && rm -rf Moralis-JS-SDK-v1
    - git clone git@github.com:MoralisWeb3/Moralis-JS-SDK-v1.git && cd Moralis-JS-SDK-v1
    - git checkout $CI_COMMIT_REF_NAME
    - npm install
    - npm run build
    - git add .
    - 'git commit -m "build: new deployment [ci skip]" --no-verify || echo "no build src changes, ignore commit failure"'
    - git push
    - npx semantic-release
